let tasks = [
  {
    id: 11,
    status: "done",
    category: "Technical Task",
    category_color: 5,
    title: "Datenbeschaffung",
    description: " Sammle relevante Daten aus dem Internet für den KI-Webbot.",
    due_date: "2023-11-29",
    priority: 2,
    assigned_to: [1, 2, 3],
    subtasks: [],
  },
  {
    id: 13,
    status: "done",
    category: "Technical Task",
    category_color: 5,
    title: "Web-Crawling-Algorithmus erstellen",
    description:
      "Entwickle einen Algorithmus, um Webseiten effizient zu durchsuchen.",
    due_date: "2023-12-22",
    priority: 3,
    assigned_to: [28, 18, 4],
    subtasks: [],
  },
  {
    id: 16,
    status: "in-progress",
    category: "Technical Task",
    category_color: 5,
    title: "Testen und Optimieren",
    description:
      "Teste den KI-Webbot auf seine Leistungsfähigkeit und optimiere ihn für bessere Ergebnisse.",
    due_date: "2023-12-23",
    priority: 2,
    assigned_to: [1, 6, 31],
    subtasks: [],
  },
  {
    id: 18,
    status: "to-do",
    category: "User Story",
    category_color: 10,
    title: "Video-Call 10:00",
    description: "\\Entwicklungsmeeting: Web-Crawling-Algorithmus\\",
    due_date: "2023-11-24",
    priority: 1,
    assigned_to: [28, 1, 18, 2, 3, 4, 5, 15, 6],
    subtasks: [],
  },
  {
    id: 17,
    status: "in-progress",
    category: "User Story",
    category_color: 10,
    title: "Video-Call 20:00",
    description: " \\Kick-off Meeting: Datenbeschaffung für KI-Webbot\\",
    due_date: "2023-11-25",
    priority: 1,
    assigned_to: [28, 1, 18, 2, 3, 4, 5, 15],
    subtasks: [],
  },
  {
    id: 19,
    status: "to-do",
    category: "User Story",
    category_color: 10,
    title: "Datenverarbeitung für den Webbot",
    description:
      " Verarbeitung der gesammelten Daten, um sie für die Nutzung im Webbot optimal aufzubereiten.",
    due_date: "2023-11-25",
    priority: 2,
    assigned_to: [18],
    subtasks: [],
  },
  {
    id: 15,
    status: "to-do",
    category: "Technical Task",
    category_color: 5,
    title: "Nutzeroberfläche erstellen",
    description:
      "Entwickle eine Benutzeroberfläche, um den KI-Webbot zu steuern und abzufragen.",
    due_date: "2023-12-28",
    priority: 2,
    assigned_to: [11, 29],
    subtasks: [{ done: false, subtask: "KI" }],
  },
  {
    id: 12,
    status: "await-feedback",
    category: "Technical Task",
    category_color: 5,
    title: "KI-Modell-Training",
    description: "Trainiere das KI-Modell mit den gesammelten Daten.",
    due_date: "2023-12-08",
    priority: 2,
    assigned_to: [5, 4, 7],
    subtasks: [{ done: false, subtask: "Ki Bot" }],
  },
  {
    id: 14,
    status: "await-feedback",
    category: "Technical Task",
    category_color: 5,
    title: "Datenverarbeitung",
    description:
      "Bereite die gesammelten Daten für die Verwendung im Webbot vor.",
    due_date: "2023-12-16",
    priority: 1,
    assigned_to: [1, 2, 5, 15],
    subtasks: [],
  },
  {
    id: 20,
    status: "in-progress",
    category: "Technical Task",
    category_color: 5,
    title: "Responsive Design erstellen",
    description: "Erstelle ein responsives Design",
    due_date: "2023-12-28",
    priority: 3,
    assigned_to: [17, 18, 5],
    subtasks: [{ done: false, subtask: "Neue Subtask" }],
  },
];

let contacts = [
  {
    id: 1,
    name: "Anna Bahr",
    initials: "AB",
    email: "anna_bahr@gmx.de",
    phone: "+12345",
    "badge-color": 5,
    userid: -1,
  },
  {
    id: 2,
    name: "Anton Mayer",
    initials: "AM",
    email: "antom@gmail.com",
    phone: "+491111111111",
    "badge-color": 4,
    userid: -1,
  },
  {
    id: 3,
    name: "Anja Schulz",
    initials: "AS",
    email: "schulz@hotmail.com",
    phone: "+493333333333",
    "badge-color": 11,
    userid: -1,
  },
  {
    id: 4,
    name: "Benedikt Ziegler",
    initials: "BZ",
    email: "benedikt-z@gmail.com",
    phone: "+492332244324",
    "badge-color": 9,
    userid: -1,
  },
  {
    id: 5,
    name: "David Eisenberg",
    initials: "DE",
    email: "davidberg@gmail.com",
    phone: "+495555555555",
    "badge-color": 4,
    userid: -1,
  },
  {
    id: 6,
    name: "Eva Fischer",
    initials: "EF",
    email: "eva@gmail.com",
    phone: "+496666666666",
    "badge-color": 6,
    userid: -1,
  },
  {
    id: 7,
    name: "Emanuel Müller",
    initials: "EM",
    email: "emanuelmueller@gmail.com",
    phone: "+49111234567",
    "badge-color": 11,
    userid: -1,
  },
  {
    id: 8,
    name: "Emmanuel Mauer",
    initials: "EM",
    email: "emmanuelma@gmail.com",
    phone: "+497777777777",
    "badge-color": 12,
    userid: -1,
  },
  {
    id: 9,
    name: "Hans Peter",
    initials: "HP",
    email: "hans@peter-test123.de",
    phone: "0049123456789",
    "badge-color": 9,
    userid: -1,
  },
  {
    id: 10,
    name: "Manuel Bauer",
    initials: "MB",
    email: "manuelbauer@gmail.de",
    phone: "+49123456789",
    "badge-color": 3,
    userid: -1,
  },
  {
    id: 11,
    name: "Marcel Brauer",
    initials: "MB",
    email: "bauer@gmail.com",
    phone: "+498888888888",
    "badge-color": 5,
    userid: -1,
  },
  {
    id: 13,
    name: "Zauberer Zander",
    initials: "ZZ",
    email: "zauberer@zander.org",
    phone: "+4928555",
    "badge-color": 7,
    userid: -1,
  },
  {
    id: 14,
    name: "Max Mustermann",
    initials: "MM",
    email: "max@mustermann.de",
    phone: "+4917647889544",
    "badge-color": 12,
    userid: 1,
  },
  {
    id: 15,
    name: "Delmor Mecom",
    initials: "DM",
    email: "delete@me.com",
    phone: "+49122334457",
    "badge-color": 7,
    userid: 3,
  },
  {
    id: 16,
    name: "Neele Emken",
    initials: "NE",
    email: "neele@emken.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 6,
    userid: 4,
  },
  {
    id: 17,
    name: "Tom Tester",
    initials: "TT",
    email: "tom@test123.de",
    phone: "00469981",
    "badge-color": 0,
    userid: 5,
  },
  {
    id: 18,
    name: "Alexander Dause",
    initials: "AD",
    email: "alexander.dause@web.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 11,
    userid: 6,
  },
  {
    id: 19,
    name: "Sebastian Brosda",
    initials: "SB",
    email: "brosda90@web.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 7,
    userid: 7,
  },
  {
    id: 20,
    name: "Reiner Janssen ",
    initials: "RJ",
    email: "reiner@jannsen.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 0,
    userid: 8,
  },
  {
    id: 23,
    name: "Martin Mick",
    initials: "MM",
    email: "martin@mick.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 7,
    userid: 9,
  },
  {
    id: 24,
    name: "Simon ",
    initials: "S",
    email: "simon@simon.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 0,
    userid: 10,
  },
  {
    id: 25,
    name: "Johanna Vitts",
    initials: "JV",
    email: "test@test.de",
    phone: "004917698284675",
    "badge-color": 4,
    userid: -1,
  },
  {
    id: 26,
    name: "René",
    initials: "R",
    email: "rene.tube992@gmail.com",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 8,
    userid: 11,
  },
  {
    id: 27,
    name: "Kevin Mentori",
    initials: "KM",
    email: "asd@asd.de",
    phone: "004923123234234",
    "badge-color": 6,
    userid: 12,
  },
  {
    id: 28,
    name: "Sebastian Brosda",
    initials: "SB",
    email: "kosmas2412@web.de",
    phone: "+49123456",
    "badge-color": 0,
    userid: 13,
  },
  {
    id: 29,
    name: "Peter Pan",
    initials: "PP",
    email: "pp@nix.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 10,
    userid: 14,
  },
  {
    id: 30,
    name: "peter pan",
    initials: "PP",
    email: "peter@pan.de",
    phone: "0017458475",
    "badge-color": 7,
    userid: -1,
  },
  {
    id: 31,
    name: "janina janssen",
    initials: "JJ",
    email: "janina@janssen.de",
    phone: "0012345232423",
    "badge-color": 8,
    userid: -1,
  },
  {
    id: 33,
    name: "Mihai",
    initials: "M",
    email: "mihai@dev.com",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 13,
    userid: 15,
  },
  {
    id: 35,
    name: "Noch Nichtda",
    initials: "NN",
    email: "nochnichtda@freenet.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 7,
    userid: 16,
  },
  {
    id: 36,
    name: "Alex L",
    initials: "AL",
    email: "alexl@leicotech.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 14,
    userid: 17,
  },
  {
    id: 37,
    name: "Noch Nichtda",
    initials: "NN",
    email: "nochnichtda@nixda.de",
    phone: "Bitte Telefonnummer eintragen",
    "badge-color": 5,
    userid: 18,
  },
  {
    id: 42,
    name: "Susi Sonnenschein",
    initials: "SS",
    email: "susisonne@test.de",
    phone: "000576467687",
    "badge-color": 14,
    userid: -1,
  },
];

let users = [
  {
    id: 1,
    name: "Max Mustermann",
    initials: "MM",
    email: "max@mustermann.de",
    password: "Test123!",
    phone: "+4917647889544",
    contacts: [14],
  },
  {
    id: 3,
    name: "Delmor Mecom",
    initials: "DM",
    email: "delete@me.com",
    password: "Sauber1!",
    phone: "+49122334457",
    contacts: [15],
  },
  {
    id: 4,
    name: "Neele Emken",
    initials: "NE",
    email: "neele@emken.de",
    password: "Pommes123!",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [16],
  },
  {
    id: 5,
    name: "Tom Tester",
    initials: "TT",
    email: "tom@test123.de",
    password: "1Q2W3e4r!",
    phone: "00469981",
    contacts: [17],
  },
  {
    id: 6,
    name: "Alexander Dause",
    initials: "AD",
    email: "alexander.dause@web.de",
    password: "Abcd1234!",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [18],
  },
  {
    id: 7,
    name: "Sebastian Brosda",
    initials: "SB",
    email: "brosda90@web.de",
    password: "Test123!",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [19],
  },
  {
    id: 8,
    name: "Reiner Janssen ",
    initials: "RJ",
    email: "reiner@jannsen.de",
    password: "Test123!",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [20],
  },
  {
    id: 9,
    name: "Martin Mick",
    initials: "MM",
    email: "martin@mick.de",
    password: "Test123!",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [23],
  },
  {
    id: 10,
    name: "Simon ",
    initials: "S",
    email: "simon@simon.de",
    password: "Test1234#",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [24],
  },
  {
    id: 11,
    name: "René",
    initials: "R",
    email: "rene.tube992@gmail.com",
    password: "<!MaYeSTiC19961998!>",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [26],
  },
  {
    id: 12,
    name: "Kevin Mentori",
    initials: "KM",
    email: "asd@asd.de",
    password: "Asd123??",
    phone: "004923123234234",
    contacts: [27],
  },
  {
    id: 13,
    name: "Sebastian Brosda",
    initials: "SB",
    email: "kosmas2412@web.de",
    password: "Pommes123!",
    phone: "+49123456",
    contacts: [28],
  },
  {
    id: 14,
    name: "Peter Pan",
    initials: "PP",
    email: "pp@nix.de",
    password: "12345678aA!",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [29],
  },
  {
    id: 15,
    name: "Mihai",
    initials: "M",
    email: "mihai@dev.com",
    password: "=}!70I3RfAg*",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [33],
  },
  {
    id: 16,
    name: "Noch Nichtda",
    initials: "NN",
    email: "nochnichtda@freenet.de",
    password: "Seltsam100!",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [35],
  },
  {
    id: 17,
    name: "Alex L",
    initials: "AL",
    email: "alexl@leicotech.de",
    password: "Seltsam100!",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [36],
  },
  {
    id: 18,
    name: "Noch Nichtda",
    initials: "NN",
    email: "nochnichtda@nixda.de",
    password: "Seltsam100!",
    phone: "Bitte Telefonnummer eintragen",
    contacts: [37],
  },
];
